### ISSUE TITLE
Mate-appearance-properties: segfault on specific combinations of themes and fonts

### ISSUE THREAD

**Issue by RichardNeill** [mate-desktop/mate-control-center#175]
The combination of (exactly):
- an Ambience-derived theme:
- the fixed-width font = Terminus
- the 2nd time the Appearance->fonts  option is opened

will result in a repeatable segfault. 
This is a really weird condition, but it is easy and reliable to reproduce.

mate-appearance-properties: ../../../../src/cairo-scaled-font.c:459: _cairo_scaled_glyph_page_destroy: Assertion `!scaled_font->cache_frozen' failed.
Aborted (core dumped)

I originally filed this report downstream, here, with more details:
https://bugs.launchpad.net/ubuntu/+source/mate-control-center/+bug/1464069

**Comment by monsta** [comment]
Weird one, I agree. Question: did you try it in only Wily?

I'd try it there later - but only after **all** MATE packages will be upgraded to 1.10. The current mix of 1.8 and 1.10 is known to cause issues (see the news post [here](https://ubuntu-mate.org/blog/ubuntu-mate-wily-beta1/)).

**Comment by sboddy** [comment]
See https://bugs.launchpad.net/ubuntu/+source/terminator/+bug/1294699 for an earlier instance of this same issue, and details of an upstream (cairo) bug report that is getting no attention for now.

**Comment by IronWolve** [comment]
Same issue, running Mate 1.12 Ambiant Gtk2/gtk3, Ubuntu Medium 10 font, opensuse tumbleweed.

mate-appearance-properties: cairo-scaled-font.c:459: _cairo_scaled_glyph_page_destroy: Assertion `!scaled_font->cache_frozen' failed.
Aborted (core dumped)

**Comment by monsta** [comment]
Ok, I confirm it in Mint 17.3. Ambiance + Terminus crashes ```mate-appearance-properties``` alright.

Here's the (huge) backtrace: http://pastebin.com/NkY0VRRQ

The backtrace confirms that the problem should be addressed in cairo, or maybe in murrine theme engine (see comments at [this bug report](https://bugs.freedesktop.org/show_bug.cgi?id=78787)).

**Comment by monsta** [comment]
So, this is the same issue as in https://github.com/mate-desktop/mate-panel/issues/328, and it is fixed by patching Murrine theme engine. It's a pity that Murrine isn't maintained upstream for years, so the patch should be applied in the distros. So I've sent the patch (in the form of debdiff) to Debian and Ubuntu, and other people sent the patch to Arch and Fedora.

Debian: https://bugs.debian.org/827134
Ubuntu: https://bugs.launchpad.net/bugs/1294699
Arch: https://bugs.archlinux.org/48294
Fedora: https://bugzilla.redhat.com/1310313

Patch itself (in the attachment): https://github.com/mate-desktop/mate-panel/issues/328#issuecomment-186539988
