### ISSUE TITLE
Window Border theme cannot be deleted

### ISSUE THREAD

**Issue by zhangxianwei8** [mate-desktop/mate-control-center#316]
#### Expected behaviour
The theme can be deleted.

#### Actual behaviour
The theme can not be deleted.

#### Steps to reproduce the behaviour
1. Open m-c-c → "Appearance" → Theme → Customize... → Window Border
2. Then, choose a theme to delete, it will be failed with tips: "Theme can not be deleted"

#### MATE general version
1.19

#### Package version
1.19.2-1

#### Linux Distribution
Fedora 27

**Comment by lukefromdc** [comment]
Issue confirmed here

**Comment by lukefromdc** [comment]
Not quite confirmed: with m-c-c from git master as of 1-8-2018, it turns out deleting a theme works fine-except that you have to restart mate-control-center to see that it is actually gone. On deletion the applied theme changes immediately.

**Comment by zhangxianwei8** [comment]
I have tested from git master as of 1-8-2018, and It works with the patch that m-c-c do not need to be restarted. @lukefromdc

**Comment by lukefromdc** [comment]
For whatever reason we got different results, don't know why

**Comment by zhangxianwei8** [comment]
I have tested on Fedora27‘s MATE version 1.19 and git master as of 1-8-2018, it's all OK. Could you confirm again. The step is deleting a theme in "Window Border". Thanks:) @lukefromdc

**Comment by lukefromdc** [comment]
Just retested. Same results as before: mate-appearance-properties (not the entire control center it turns out) must be restarted for the deleted theme to no longer appear in the icon view. Not only that, so long as mate-appearance-properties remains open, the deleted theme can be selected and applied again. Once mate-appearance-properties has been closed and opened again, the deleted theme is gone. This is on git master as of 1-8-2018 with Debian Unstable. Customized window borders were the test subject.

**Comment by zhangxianwei8** [comment]
When you delete the theme, the result is success or failure?

**Comment by lukefromdc** [comment]
Mixed: at first deletion appears to fail, but when you close and reopen mate-appearance-properties (the window from which you change themes in mate-control-center) the customized theme is gone.

**Comment by zhangxianwei8** [comment]
Did you test with the patch?

**Comment by lukefromdc** [comment]
I did earlier, results were exactly the same.

**Comment by zhangxianwei8** [comment]
Oh, when you delete the theme, is the directory " /usr/share/themes/Menta/metacity-1" gone?

**Comment by zhangxianwei8** [comment]
Hi, could you test for me with this PR #317,  thanks:) @monsta @raveit65

**Comment by lukefromdc** [comment]
Anything in /usr/share/themes cannot be deleted without root priviliges, user themes are stored in ~.themes. 

I looked there, and found that on deleting a theme it is immediately removed from that directory (all of it) but since it can still be selected until mate-appearance-properties is closed I am guessing it is still loaded in RAM. Remember that to delete a theme you must first select it, and that switches to it.

The theme then remains available so long as mate-appearance-properties is open. If you delete the theme but then switch back to it, then close mate-appearance-properties and reopen it, it comes up as "custom" and is no longer storied in ~/.themes, from which it was removed the moment it was deleted.

**Comment by zhangxianwei8** [comment]
So, is this a bug?

**Comment by lukefromdc** [comment]
I don't see it as a big deal, and it's not a failure of the deleted theme to be removed from storage.

**Comment by zhangxianwei8** [comment]
But if use "marco-1", it always failed when deleting the Window Border theme, never success.

**Comment by raveit65** [comment]
As expected the PR works with using a theme from home dir.
After deleting the metacity theme the custom thumbnail is updated **before** i closed m-a-p window.
Here with WinMe metacity theme which is next one in order.
![bildschirmfoto zu 2018-01-09 11-15-23](https://user-images.githubusercontent.com/961604/34716270-9c16ef5e-f52f-11e7-91f0-9d90d9c6e3bc.png)

The thumbnail from Ubuntu-Legay-theme which i used for testing will never been updated, with or without restarting m-a-p.
After restart:
![bildschirmfoto zu 2018-01-09 11-16-58](https://user-images.githubusercontent.com/961604/34716428-1fc1a876-f530-11e7-9441-7bb4da20de70.png)

No wonder, because the metacity theme is mentioned in index.theme file and m-a-p complains always about the missing icon-theme here.
So, no need to create a new thumbnail for m-a-p, imo.
Looks ready to go for me.
