### ISSUE TITLE
default-application: weird selection box for file-managers

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-control-center#402]
#### Expected behaviour
DropdownBox for file-manager should look like the others.

#### Actual behaviour
Icons and title are misplaced in DropdownBox for file-manager.
![default-applications](https://user-images.githubusercontent.com/961604/49695416-fd6b4080-fb9a-11e8-9482-b04533803829.png)

#### Steps to reproduce the behaviour
install m-c-c from master

#### MATE general version
Master branch

#### Package version
mate-control-center-1.21.2-2.fc28.x86_64

#### Linux Distribution
fedora

#### Link to downstream report of your Distribution
1.22 isn't released, so nothing in distros.

**Comment by lukefromdc** [comment]
The only icon problem I get with this is for SpaceFM, where the icon is oversized and the bottom half gets cut off. Presumably these are different symptoms of the same issue?

**Comment by zhangxianwei8** [comment]
The gnome's nautilus icons cause.
"Preferred Applications" use 22x22 icons, but all of gnome's nautilus icon are 512x512:
```
[root@localhost hicolor]# pwd
/usr/share/icons/hicolor
[root@localhost hicolor]# file */apps/org.gnome.Nautilus.png
16x16/apps/org.gnome.Nautilus.png:   PNG image data, 512 x 512, 8-bit/color RGBA, non-interlaced
22x22/apps/org.gnome.Nautilus.png:   PNG image data, 512 x 512, 8-bit/color RGBA, non-interlaced
24x24/apps/org.gnome.Nautilus.png:   PNG image data, 512 x 512, 8-bit/color RGBA, non-interlaced
32x32/apps/org.gnome.Nautilus.png:   PNG image data, 512 x 512, 8-bit/color RGBA, non-interlaced
48x48/apps/org.gnome.Nautilus.png:   PNG image data, 512 x 512, 8-bit/color RGBA, non-interlaced
512x512/apps/org.gnome.Nautilus.png: PNG image data, 512 x 512, 8-bit/color RGBA, non-interlaced
```
The latest code has removed these icons, using svg icon instead of png icons.
https://github.com/GNOME/nautilus/commit/564b9dcbd70936d7d1b415979f4d9429e4e0cec0#diff-bf131e85e22cb01e57f70de832d03e7c

**Comment by lukefromdc** [comment]
OK, these two related rendering problems both have icons shown oversize and trimmed to fit the box. That means the icon rendering needs to be scaled unconditionally unless there is a way to scale icons if and only if they are oversize.

**Comment by tamplan** [comment]
Hi,

Perhaps yet fixed by PR #444.

Tested just today on Fedora 30 and code from mate-control-center-master branch for SpaceFM and Nautilus:
![Capture du 2019-06-09 11-28-51](https://user-images.githubusercontent.com/50292710/59157428-83186c00-8aaa-11e9-94eb-61363c22146a.png)

Not tested with DropdownBox (unused).

Regards

**Comment by raveit65** [comment]
For some reasons i can't reproduce the issue any more.

**Comment by lukefromdc** [comment]
I can confirm that SpaceFM, Nautilus, Caja all get the same size icons now in this dialog. I used to get this with SpaceFM and now do not, so it looks like this is confirmed fixed
