### ISSUE TITLE
Alt + Ctl + Backspace doesn't restart the X server.

### ISSUE THREAD

**Issue by crhy** [mate-desktop/mate-control-center#613]
#### Expected behaviour
It's the 3 finger salute.

#### Actual behaviour
Does Nothing.

#### Steps to reproduce the behaviour
Press Alt+Ctl+Backspace while desktop running.

#### MATE general version
Whatever is in the latest Mint 20.1 Beta.

#### Package version
Whatever is in the latest Mint 20.1 Beta.

#### Linux Distribution
Mint 20.1 Beta.

#### Link to bugreport of your Distribution (requirement)
https://github.com/linuxmint/mint20.1-beta/issues/89

**Comment by lukefromdc** [comment]
This is not controlled by the desktop environment, but rather by setting a custom keyboard shortcut to terminate the x server. I have forgotten exactly how this is done, as I set it up years ago (probably 2009) and it does not show up in mate-control-center. This began with a "don't zap" patch to xorg itself, not GNOME, MATE etc. 

Linuxmint could set this up by default, probably they don't to keep new users from losing their work. This feature for that reason has not been the default in Xorg since 2009. Closing as this is an Xorg and not a MATE (or old GNOME 2) change and would not be a decision ever made by a DE, only by distros or by Xorg reverting the changed default.
